services:
  # Web Service
  - type: web
    name: gam106asm
    env: docker
    region: singapore
    plan: free
    branch: main
    dockerfilePath: ./Dockerfile
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_URLS
        value: http://+:10000
      - key: ConnectionStrings__DefaultConnection
        sync: false
      - key: Jwt__Key
        generateValue: true
      - key: Jwt__Issuer
        value: GAM106ASM
      - key: Jwt__Audience
        value: UnityClient
      - key: Jwt__ExpiryMinutes
        value: 60
      - key: SmtpHost
        value: smtp.gmail.com
      - key: SmtpPort
        value: 587
